-- AlterTable
ALTER TABLE "ingredients" ALTER COLUMN "amount" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "description" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "instructionRef" SET DATA TYPE VARCHAR(500);
